# This is a basic workflow to help you get started with Actions

name: Build and Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup JFrog CLI (Foo)
        uses: jfrog/setup-jfrog-cli@v4.5.6
        env:
          # JFrog Platform url
          JF_URL: ${{ vars.JF_URL }} # or 'https://acme.jfrog.io'

          # Basic authentication credentials
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

      - name: Test Connection to Artifactory
        run: |
          jf rt ping

      - name: Configure Gradle Integration
        run: |
          jf gradle-config \
          --repo-resolve asaftest-gradle-dev \
          --repo-deploy asaftest-gradle-dev \

      - name: Build Our Project
        run: |
          jf gradle build --build-name asaf-test --build-number ${{ github.run_number }}